config/routes.rb
Rails.application.routes.draw do
  devise_for :users,controllers:{
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    recoverables: 'users/recoverables'
  }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")

  root "products#index" 

  resources :users, except: [:new, :create] do
    resources :orders
    resources :order_items, only: [:update]
    member do
      get '/products', to: 'users#products'
    end
  end

  namespace :admin do
    resources :roles
  end

  namespace :admin do
    resources :products, only: [:index]
  end

  resources :products do
    member do
      get '/product_stock', to: 'products#product_stocks'
    end
  end 

  namespace :admin do
    resources :categories do
    end
  end

  resources :categories do
    member do
      get '/product/:id', to: 'products#show', as: :see_product
    end
  end
  

  resources :product_stocks, only: [:index, :update, :create, :destroy, :edit]

  resources :address, only: [:index, :update, :create, :destroy, :edit]


  resources :cart_items, path: :cart, only: [:index, :create, :destroy] do
    member do
      patch '/increment', to: 'cart_items#increment'
      patch '/decrement', to: 'cart_items#decrement'
    end
  end

  get '/orders', to: 'orders#my_order'
  post '/order_verify/:id', to: 'orders#create'
  get ':id/payment', to: 'orders#payment', as: "payment"
  get '/checkout', to: 'orders#new'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :user_roles, dependent: :destroy
  has_many :roles, through: :user_roles
  has_many :products
  has_many :cart_items
  has_many :orders
  has_many :addresses

  validates :email, presence: true, uniqueness: true 
        
  enum status: {
    active: 0,
    inactive: 1
  }
  
  def admin?
    role_ids.include?(1)
  end

  def owner?
    role_ids.include?(3)
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super  
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

    protected
  
    # The path used after confirmation.
    def after_confirmation_path_for(resource_name, resource)
      sign_in(resource_name, resource)
      # super
      root_path
    end
  # end
  
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # # GET /resource/sign_up
  def new
    @roles = Role.where.not(title: 'Admin')
    super
  end

  # POST /resource
  def create
    super
    session[:cart_items].each do |cart_item|
      CartItem.create(cart_item)
    end
    session[:cart_items] = []
    
  end

  # GET /resource/edit
  # def edit
  #   @user = User.new
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit( :first_name, :last_name, :email, :password, :password_confirmation, role_ids: [] )
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    if User.find_by(email: params[:user][:email]).blank?
      redirect_to new_user_session_path, alert: "User Doesn't Exist"
      return  
    elsif User.find_by(email: params[:user][:email]).inactive?
      redirect_to new_user_session_path, notice: "Your Status Is Inactive !!! Contact Support" 
    else
      super
      unless session[:cart_items].blank?
        session[:cart_items].each do |cart_item|
         CartItem.create(cart_item.merge(user_id: current_user.id))
        end
        session[:cart_items] = []
      end
    end
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected
  # def after_sign_in_path_for(resource)
  #   redirect_to home_users_path, notice: "Signed In Succesfully"
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in) do |user_params|
  #     user_params.permit(:email, :password)
  #   end
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    respond_to do |format|
      format.html
      format.json { render json: UserDatatable.new(params, view_context: view_context) }
    end    
  end

  def new
    @user = User.new
    @roles = Role.where.not(title: "Admin")  
  end

  def create
    @user = User.new(user_params)
    roles = role_params[:roles]

    if roles.present?
      roles = roles.map! { |role| role.to_i }
      @user.roles = Role.where(id: roles)
    end

    if @user.save
      redirect_to home_path, notice: "Created Successfully"
    else
      flash.now[:alert] = @user.errors.full_messages.to_sentence
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize user
    @roles = Role.where.not(title: "Admin") 
  end

  def show
    authorize user
  end

  def update
    authorize user
    if @user.update(user_params)
      roles = params[:user][:roles]
      if roles.blank?
        flash.now[:alert] = "User must have at least one role"
        render :edit, status: :unprocessable_entity
        return
      end
      roles.map! { |role| role.to_i }
      @user.update(role_ids: roles)
      if user.admin?
        redirect_to users_path, notice: "User Updated Successfully"
      else
        redirect_to root_path, notice: "User Updated Successfully"
      end
    else
      flash.now[:alert] = @user.errors.full_messages.to_sentence
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize user 
    begin
      @user.destroy
      redirect_to users_path, notice: "Successfully Deleted"
    rescue ActiveRecord::RecordNotFound => e
      redirect_to '/404'
    end
  end

  def products
    @products = Product.where(user_id: current_user.id)
    @stock={}
    @products.each do |product|
      @stock[product] = product.product_stocks.where(transaction_type: 1).pluck(:quantity).sum - product.product_stocks.where(transaction_type: 0).pluck(:quantity).sum
    end
  end

  private

  def user
    @user ||= User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :status)
  end

  def role_params
    params.require(:user).permit(roles: [])  
  end
end

app/views/users/_form.html.erb
<div class="d-flex input-fields">
    <div class="mt-3">
        <%= f.text_field :first_name ,placeholder:" First Name", class:"form-control"  %>
        <% @user.errors.full_messages_for(:first_name).each do |error_message| %>
            <p class="text-danger m-0 p-0"> *<%= error_message %></p>
        <% end %>
    </div>
    <div class="mt-3">
        <%= f.text_field :last_name ,placeholder:" Last Name", class:"form-control"  %>
    </div>
    <div class="mt-3">
        <%= f.text_field :email ,placeholder:" Email", class:"form-control"  %>
        <% @user.errors.full_messages_for(:email).each do |error_message| %>
            <p class="text-danger m-0 p-0"> *<%= error_message %></p>
        <% end %>
    </div>
    <div class="mt-3">
        <%= f.password_field :password, placeholder:" Password", class:"form-control"  %>
    </div>
    <div class="mt-3">
        <%= f.password_field :password, placeholder:" Confirm Password", class:"form-control"  %>
    </div>

    <div class="mt-3 d-flex justify-content-center"> 
        <% Role.all.each do |role| %>
            <% if role.title != "Admin" %>
                <%= f.check_box :roles, {multiple: true,checked: @user.roles.map{|rol| rol.id}.include?(role.id)}, role.id, nil %>
                <%= f.label :roles, role.title, class:"mx-2" %>  
            <% end %>
        <% end %>
    </div>
</div>

app/views/users/edit.html.erb
<div>
  <div class="container">
    <div class="form-box shadow-lg" style="height: 55vh;">
    
    <%= form_for @user do |f| %>
    <h1 class="text-dark mt-3">Update Form</h1>
      <%# = render "users/shared/error_messages", resource: resource %>

      <div class="d-flex input-fields">
        <div class="mt-3">
            <%= f.text_field :first_name ,placeholder: " First Name", class: "form-control"  %>
            <% @user.errors.full_messages_for(:first_name).each do |error_message| %>
                <p class="text-danger m-0 p-0"> *<%= error_message %></p>
            <% end %>
        </div>
        <div class="mt-3">
            <%= f.text_field :last_name ,placeholder: " Last Name", class: "form-control"  %>
        </div>
        <div class="mt-3">
            <%= f.text_field :email ,placeholder: " Email", class: "form-control"  %>
            <% @user.errors.full_messages_for(:email).each do |error_message| %>
                <p class="text-danger m-0 p-0"> *<%= error_message %></p>
            <% end %>
        </div>
        
        <div class="mt-3 d-flex justify-content-center"> 
        <% @roles.each do |role| %>
          <%= f.check_box :roles, {multiple: true,checked: @user.roles.map{|rol| rol.id}.include?(role.id)}, role.id, nil %>
          <%= f.label :roles, role.title, class:"mx-2" %>  
        <% end %>
       
    </div>
     <div class="d-flex justify-content-center gap-2">
      <%= f.label :status, 'Status: ' %>
      <%# = binding.pry %>
      <%= f.select :status, options_for_select(User.statuses.map { |status, value| [status.to_s.humanize, status.to_s]}, selected: [@user[:status]]), class: "form-control" %>
     </div>
        
    </div>
    <div class="actions mb-3">
        <%= f.submit "Update" , class:"btn btn-primary"%>
      </div>
    <% end %>
  </div>
  </div>
</div>

app/views/users/index.html.erb
<%= stylesheet_link_tag "users.css" %>



<div class="mx-5">

    <h1 align="center" class="my-4 pt-5">Registered User List</h1>

    <table align="center" class="shadow" id="users-datatable" data-source="<%= users_path(format: :json) %>">
    <thead>
        <tr class="border-bottom">
            <th>
                ID
            </th>
            <th>
                First Name
            </th>
            <th>
                Last Name
            </th>
            <th>
                Email
            </th>
            <th>
                Roles
            </th>
            <th>
                Status
            </th>
            <th>
                Actions
            </th>
        </tr>
    </thead>

        
        
    </table>

</div>

<!-- <div class="d-flex justify-content-center mt-5"> -->
  <%#  if params[:page].to_i > 1 %>
   <!-- <div class=""><%= link_to "Previous", users_path(page: params[:page].to_i - 1), class:"btn btn-outline-secondary mx-4" %></div> -->
  <%#  end %>
  <!--  -->
  <%#  if @users.size == @per_page %>
    <%# if !params[:page] %>
      <!-- <div class=""><%= link_to "Next", users_path(page: 2), class:"btn btn-outline-secondary" %></div> -->
    <%# else %>
      <!-- <div class=""><%= link_to "Next", users_path(page: params[:page].to_i + 1), class:"btn btn-outline-secondary" %></div> -->
    <%# end %>
  <%#  end %>
  <!--  -->
<!-- </div> -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.1/jquery.min.js"></script>

<script src="https://cdn.datatables.net/2.2.1/js/dataTables.js"></script>

<%= javascript_include_tag 'users.js' %>

app/views/users/new.html.erb
<%= stylesheet_link_tag "new_user.css" %>

<div>
    <div class="container">
        <div class="form-box shadow-lg">
            <%= form_for @user, html: { class: 'form-control d-flex justify-center' } do |f| %>
                <h1 class="text-dark">Registration Form</h1>
                    <%= render "form", f: f %>
                    <div>
                        <%= f.submit "Register", class:"btn btn-outline-primary" %>
                    </div>
            <% end %>
        </div>
    </div>
</div>

app/views/users/products.html.erb
<%= stylesheet_link_tag "users.css"%>
<%= javascript_include_tag 'product_modal.js' %>


<% unless @title %>
  <h1 align="center" class="my-4 pt-5">My Product </h1>
<% else %>
  <h1 align="center" class="my-4 pt-5">Search Results for "<%= @title %>"</h1>
<% end %>
<table align="center" class="shadow" id="table">
    <tr class="border-bottom">
        <th>
          Seriel No
        </th>
        <th class="w-200px">
           Image
        </th>
        <th>
          Name
        </th>
        <th>
          Price
        </th>
        <th>
          Category
        </th>
        <th>
          Stocks Available
        </th>
        <th>
          Actions
        </th>
    </tr>

    <% @products.each_with_index do |product,i| %>
      <tr class="shadow-sm">
        <div class="row ">
          <td>
              <%= i+1 %>
          </td>
          <td class="d-flex justify-content-center ">
                <%= image_tag product.images.first, class:"img-fluid w-75"%>
          </td>
          <td>
              <%= product.name %>
          </td>
          <td>&#8377;<%= product.price %></td>
          <td><%= product.categories.map{|category| category.name}.join(",") %></td>  
          <td>
            <%= link_to @stock[product], product_stock_product_path(product)%>
          </td>     
          <td class="fs-1">
              <%= link_to product_path(product),class: "btn text-primary btn-lg" do %>
                  <i class="bi bi-eye-fill" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Show product"></i>
              <% end %>
              <%= link_to edit_product_path(product), class: "btn text-dark btn-lg" do %>
              <i class="bi bi-pencil-fill" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Edit product"></i>
              <% end %>
              
              <%= link_to product_path(product), data: { turbo_method: :delete, turbo_confirm: 'Are you sure to delete the product?' }, class: "btn  btn-lg text-danger" do %>
              <i class="bi bi-trash-fill" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Delete product"></i>
              <% end %>

              <button class="btn btn-lg text-success" data-bs-target="#exampleModalToggle" data-bs-toggle="modal" data-id=<%= product.id %> data-name=<%= product.name %>>
                <i class="bi-plus-circle" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Stock Opertion"></i>
              </button>         
          </td>   
        </div>
      </tr>
    <% end %>
    
</table>

<div class="modal fade" id="exampleModalToggle" aria-hidden="true" aria-labelledby="exampleModalToggleLabel" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalToggleLabel">Modal 1</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= form_for ProductStock.new, url: product_stocks_path ,html: {class: "h-65"} do |f|%>
        <div>
          <%= f.hidden_field :product_id %>
          <%= f.label :transaction_type, 'Transaction Type: ', class: "mx-2"%>
          <%= f.select :transaction_type, options_for_select(ProductStock.transaction_types.map { |type, value| [type.to_s.humanize, type.to_s]}), {},class: "form-select"%>
          <br>
          <%= f.number_field :quantity, placeholder: "Quantity", class:"form-control mb-4"%>
        </div>
        <div class="d-flex flex-column align-items-center my-4 gap-3">
          <%= f.submit "Submit", class: "btn btn-primary "%>
        </div>
        </div>
      <%end%>
      
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= stylesheet_link_tag "users_show.css"%>

<div class="d-flex align-items-center main">
    <div class = "container d-flex justify-content-center align-items-center shadow p-3 mb-5 bg-body-tertiary rounded show_container flex-column w-50 h-50 mt-5">
    <p class="h1 text-center mb-5">My Profile</p>

    <div class = "mb-5">
        <span class = "text-center fw-medium fs-4">First Name : </span> 
        <span class = "fw-light fs-5"><%= @user.first_name%></span>
    </div>
    <div class = "mb-5">
        <span class = "text-center fw-medium fs-4">Last Name : </span> 
        <span class = "fw-light fs-5"><%= @user.last_name%></span>
    </div>

    <div class = "mb-5">
        <span class = "text-center fw-medium fs-4">Email : </span> 
        <span class = "fw-light fs-5"><%= @user.email%></span>
    </div>

    <div class = "mb-2">
        <span class = "text-center fw-medium fs-4">Roles : </span>
        <span class = "fw-light fs-5"><%= @user.roles.map{|role| role.title}.join(",")%></span>
    </div>

    <div class = "mt-5">
        <%= link_to "Edit", edit_user_path(current_user), class: "btn btn-primary btn-lg"%>
    </div>
    </div>
    
</div>