config/routes.rb
Rails.application.routes.draw do
  devise_for :users,controllers:{
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    recoverables: 'users/recoverables'
  }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")

  root "products#index" 

  resources :users, except: [:new, :create] do
    resources :orders
    resources :order_items, only: [:update]
    member do
      get '/products', to: 'users#products'
    end
  end

  namespace :admin do
    resources :roles
  end

  namespace :admin do
    resources :products, only: [:index]
  end

  resources :products do
    member do
      get '/product_stock', to: 'products#product_stocks'
    end
  end 

  namespace :admin do
    resources :categories do
    end
  end

  resources :categories do
    member do
      get '/product/:id', to: 'products#show', as: :see_product
    end
  end
  

  resources :product_stocks, only: [:index, :update, :create, :destroy, :edit]

  resources :address, only: [:index, :update, :create, :destroy, :edit]


  resources :cart_items, path: :cart, only: [:index, :create, :destroy] do
    member do
      patch '/increment', to: 'cart_items#increment'
      patch '/decrement', to: 'cart_items#decrement'
    end
  end

  get '/orders', to: 'orders#my_order'
  post '/order_verify/:id', to: 'orders#create'
  get ':id/payment', to: 'orders#payment', as: "payment"
  get '/checkout', to: 'orders#new'
end

app/views/shared/_card.html.erb
<div class="card" style="width: 18rem;">
  <img src="..." class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>

app/views/shared/_flash.html.erb
<%= stylesheet_link_tag 'flash.css' %>
<div id="flash" class="flash d-flex mt-2 me-4 flex-row justify-content-center">
    <% if notice.present? %>
        <div class="alert alert-info alert-dismissible position-absolute z-3 m-auto top-20">
            <%= notice %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            
        </div>
    <% end %>
    <% if alert.present? %>
        <div class="alert alert-warning alert-dismissible position-absolute z-3 m-auto top-20">
            <strong><%= alert %></strong>
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    <% end %>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-light bg-primary justify-content-between py-3 mb-4">
  <!-- Logo or Branding -->
  <span class="navbar-brand ms-4">
    <%= link_to 'Ekaart App', root_path, class: "text-decoration-none text-white" %>
  </span>
  
  <!-- Navbar Content: Links and User Info -->
  <div class="d-flex align-items-center rounded-pill">
    <%= form_tag root_path, method: :get, html: {class: "rounded-pill"} do %>
      <div class="input-group bg-white">
        <%= text_field_tag :search, params[:search], placeholder: "Search for products", class: "form-control border-0", name: "search" %>
          <button class="btn btn-outline-success border-0" type="submit">
            Search
          </button>
      </div>
    <% end %> 

   <div class="mx-4">
     <%= link_to cart_items_path do %>
      <button type="button" class="btn btn-primary position-relative">
        Cart <i class="bi bi-cart-fill text-white position-relative fs-5">
          <% if current_user and current_user.cart_items.count != 0 %>
            <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill text-bg-danger fst-normal" style="font-size: 10px"><%= current_user.cart_items.count %>
          </span>
          <% end %>
          <% unless session[:cart_items].blank? %>
            <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill text-bg-danger fst-normal" style="font-size: 10px"><%= session["cart_items"].count %>
          </span>
          <% end %>
        </i> 
        
      </button>
    <% end %>
   </div>
    

    <% if user_signed_in? %>
      <!-- Display Welcome Message -->
      <span class="px-3 fs-6 fw-semibold text-white">
        Welcome, <%= current_user.first_name %>
      </span>
       

      <!-- Admin Dropdown: Visible only if the user is an admin -->
      <% if current_user.admin? %>
        <div class="dropdown mx-2">
          <button class="btn btn-primary dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Admin Options
          </button>
          <ul class="dropdown-menu">
            <%= link_to 'Add User +', new_user_registration_path, class: "dropdown-item" %>
            <%= link_to 'Roles', admin_roles_path, class: "dropdown-item" %>
            <%= link_to 'Users', users_path, class: "dropdown-item" %>
            <%= link_to 'Categories', admin_categories_path, class: "dropdown-item" %>
           <%= link_to 'Products', admin_products_path, class: "dropdown-item" %>
           <%= link_to 'Stocks', product_stocks_path, class: "dropdown-item" %>
          </ul>
        </div>
      <% end %>
       <% if current_user.owner? %>
       <div class="dropdown mx-2">
          <button class="btn btn-primary dropdown-toggle fw-semibold" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Owner Options
          </button>
          <ul class="dropdown-menu">
            <%= link_to 'Add Product +', new_product_path, class: "dropdown-item" %>
            <%= link_to 'Orders', user_orders_path(current_user), class: "dropdown-item" %>
            <%= link_to 'My Products', products_user_path(current_user), class: "dropdown-item" %>
            <%= link_to 'Stocks Transactions', product_stocks_path, class: "dropdown-item" %>  
          </ul>
        </div>
          
       <% end %>

      <!-- User Profile Dropdown -->
      <div class="dropdown mx-3 me-5">
        <button class="btn btn-primary fw-semibold dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          My Profile
        </button>
        <ul class="dropdown-menu">
          <li><%= link_to 'Profile', user_path(current_user), class: "dropdown-item"%></li>
          <li><%= link_to 'Edit Profile', edit_user_path(current_user), class: "dropdown-item"%></li>
          <li><%= link_to orders_path, class: "dropdown-item" do %>
             My Orders  <i class="bi bi-bag-fill"></i>
          <% end %>
          </li>
          <li><%= link_to 'Logout', destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to log out?' }, class: "dropdown-item" %></li>
        </ul>
      </div>
    
    <% else %>
      <!-- If the user is not signed in, show sign-in and sign-up links -->
      <%= link_to user_session_path, class: "mx-1 btn btn-primary" do %>
      <div class="mx-2 text-white">
        <span>Sign In</span>
        <i class="bi bi-box-arrow-in-right"></i>
      </div>
      <% end %>
      
      <%= link_to new_user_registration_path, class: "mx-1 btn btn-primary"  do %>

      <div class="mx-2 text-white">
        <span>Sign Up</span>
        <i class="bi bi-person-plus-fill"></i>
      </div>
      
      <% end %>
      
    <% end %>
    
  </div>
</nav>