config/routes.rb
Rails.application.routes.draw do
  devise_for :users,controllers:{
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    recoverables: 'users/recoverables'
  }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")

  root "products#index" 

  resources :users, except: [:new, :create] do
    resources :orders
    resources :order_items, only: [:update]
    member do
      get '/products', to: 'users#products'
    end
  end

  namespace :admin do
    resources :roles
  end

  namespace :admin do
    resources :products, only: [:index]
  end

  resources :products do
    member do
      get '/product_stock', to: 'products#product_stocks'
    end
  end 

  namespace :admin do
    resources :categories do
    end
  end

  resources :categories do
    member do
      get '/product/:id', to: 'products#show', as: :see_product
    end
  end
  

  resources :product_stocks, only: [:index, :update, :create, :destroy, :edit]

  resources :address, only: [:index, :update, :create, :destroy, :edit]


  resources :cart_items, path: :cart, only: [:index, :create, :destroy] do
    member do
      patch '/increment', to: 'cart_items#increment'
      patch '/decrement', to: 'cart_items#decrement'
    end
  end

  get '/orders', to: 'orders#my_order'
  post '/order_verify/:id', to: 'orders#create'
  get ':id/payment', to: 'orders#payment', as: "payment"
  get '/checkout', to: 'orders#new'
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def index
    if user_signed_in?
      @cart_items = CartItem.where(user_id: current_user.id).order(:created_at)
    else
      @cart_items = session[:cart_items]
      if @cart_items.blank?
        @cart_items = []
      end
    end
    @total = @cart_items.inject(0){ |sum,item| sum + (Product.find(item["product_id"]).price * item["quantity"].to_i) }
  end

  def create
    if user_signed_in?
      @cart_item = CartItem.new(cart_params)
      
      if current_user.cart_items.pluck(:product_id).include?(cart_params[:product_id].to_i)
        cart_item = current_user.cart_items.find_by(product_id: cart_params[:product_id].to_i)
        cart_item.quantity += 1
        cart_item.save
        redirect_to cart_items_path, notice: "Added To Cart Successfully"
      else
        if @cart_item.save
          redirect_to cart_items_path, notice: "Added To Cart Successfully"
        else
          flash.now[:alert] = @cart_item.errors.full_messages.join(', ')
          render :new, status: :unprocessable_entity
        end
      end
    else
      if session[:cart_items].blank?
        session[:cart_items] = []
      end

      cart_item = session[:cart_items].find { |item| item["product_id"] == cart_params[:product_id] }

      if cart_item
        cart_item["quantity"] = (cart_item["quantity"].to_i + 1).to_s
        notice_message = "Added To Cart Successfully"
      else
        session[:cart_items] << cart_params
        notice_message = "Added To Cart Successfully"
      end
      redirect_to cart_items_path, notice: notice_message
    end
  end

  def increment
    if user_signed_in?
      @cart_item = CartItem.find(params[:id])
      if @cart_item.quantity == 10
        redirect_to cart_items_path, alert: "Maximum 10 Quantity Can Be Ordered"
      elsif @cart_item.product.count_stocks <= @cart_item.quantity
        redirect_to cart_items_path, alert: " Sorry, This Quantity Is Not Availabe"
      else
        @cart_item.update(quantity: (@cart_item.quantity + 1))
        redirect_to cart_items_path, notice: "Quantity Added Successfully"
      end
    else
      cart_item = session[:cart_items][params[:id].to_i]
      cart_item["quantity"] = (cart_item["quantity"].to_i + 1).to_s
      redirect_to cart_items_path, notice: "Quantity Added Successfully"
    end
    
  end

  def decrement
    if user_signed_in?
      @cart_item = CartItem.find(params[:id])
      if @cart_item.quantity == 1
        redirect_to cart_items_path, alert: "Quantity Can Not Be Zero"
      else
        @cart_item.update(quantity: (@cart_item.quantity - 1))
        redirect_to cart_items_path, notice: "Quantity Reduced Successfully"
      end
    else
      cart_item = session[:cart_items][params[:id].to_i]
      if cart_item["quantity"] == "1"
        redirect_to cart_items_path, alert: "Quantity Can Not Be Zero"
      else
        cart_item["quantity"] = (cart_item["quantity"].to_i - 1).to_s
        redirect_to cart_items_path, notice: "Quantity Reduced Successfully"
      end
    end
  end

  def destroy
    if user_signed_in?
      @cart_item = CartItem.find(params[:id])
      @cart_item.destroy
      redirect_to cart_items_path, notice: "Item Removed From Cart Successfully"
    else
      session[:cart_items].delete_at(params[:id].to_i)
      redirect_to cart_items_path, notice: "Item Removed From Cart Successfully"
    end
  end

  private

  def cart

  end

  def cart_params
    params.require(:cart_item).permit(:quantity, :product_id, :user_id)
  end
end

app/views/cart_items/index.html.erb
<%= stylesheet_link_tag 'cart.css' %>

<% unless @cart_items.blank? %>
  <div class="cart bg-light">
    <div class="row">
      <div class="fs-3 mb-3">
        Cart
      </div>
      
      
      <div class="col-md-9 ">
        <% @cart_items.each do |cart_item| %>
          <div class="shadow bg-white">
            <div class="row p-4">
              <div class="col-md-3">
                <%= image_tag Product.find(cart_item["product_id"]).images.first, class: "h-300" %>
              </div>
              <div class="col-md-6">
                <div class="fs-4">
                  <%= Product.find(cart_item["product_id"]).name %>
                </div>
                <div class="text-secondary">
                  <%= Product.find(cart_item["product_id"]).description  %>
                </div>
                <div class="d-flex align-items-center text-secondary mt-3">
                  <span class="fs-6 fw-medium">Quantity :</span>
                    <% if user_signed_in? %>
                      <%= link_to '-', decrement_cart_item_path(cart_item.id), class: "btn text-secondary", data: { turbo_method: :patch } %>
                    <% else %>
                      <%= link_to '-', decrement_cart_item_path(@cart_items.index(cart_item)), class: "btn text-secondary", data: { turbo_method: :patch } %>
                    <% end %>
                    <div class="secondary mx-3 fs-6">
                      <%= cart_item["quantity"] %>
                    </div>
                    
                    <% if user_signed_in? %>
                      <%= link_to '+', increment_cart_item_path(cart_item.id), class: "btn text-secondary", data: { turbo_method: :patch } %>
                    <% else %>
                      <%= link_to '+', increment_cart_item_path(@cart_items.index(cart_item)), class: "btn text-secondary", data: { turbo_method: :patch } %>
                    <% end %>
                    
                    
                </div>
                <div class="mt-4">
                  <% if user_signed_in? %>
                    <%= link_to 'Remove From Cart', cart_item_path(cart_item.id), class: "btn btn-orange", data: {turbo_method: :delete} %>
                  <% else %>
                     <%= link_to 'Remove Item', cart_item_path(@cart_items.index(cart_item)), class: "btn btn-orange", data: {turbo_method: :delete} %>
                  <% end %>
                </div>
              </div>
              <div class="col-md-3">
                <i class="bi bi-check-circle-fill text-success"></i>
                Deliver By <%= (Date.current + 7.day).strftime("%B %d")
 %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <div class="col-md-3  h-auto">
        <div class="p-3 bg-white shadow">
          <div class="price-heading border-bottom border-secondary">
            Price Details
          </div>
          <div class="mt-2" >
            <% @cart_items.each do |cart_item| %>
             <div class="d-flex my-3 justify-content-between text-secondary">
               <div>
                <%= Product.find(cart_item["product_id"]).name %> x 
              <%= cart_item["quantity"] %>
               </div>
              
              <div class="ms-3">
                &#8377;<%= Product.find(cart_item["product_id"]).price * cart_item["quantity"].to_i %>
              </div>
             </div>
            <% end %>
            <div class="delivery mt-4 border-bottom border-dark pb-3">
              <div class="d-flex justify-content-between text-secondary">
                Delivery Charges
                <div>
                  &#8377; 50.0
                </div>
              </div>
            </div>
            <div class="delivery mt-4 border-bottom border-dark pb-3">
              <div class="d-flex justify-content-between fw-medium">
                Total
                <div>
                  &#8377; <%= @total + 50 %>
                </div>
              </div>
            </div>
          </div>
          <div class="d-flex justify-content-end">
            <!-- <div class="btn btn-primary mt-4"> -->
              <!-- Order Now -->
            <!-- </div> -->
            <%= link_to 'Check Out', checkout_path, class: "btn btn-primary mt-4" %>
          </div>
          
        </div>
        
      </div>
    </div>
  </div>
<% else %>
  <h1 class="text-center mt-5 pt-5">No Items In The Cart</h1>
<% end %>





<div class="modal fade" id="exampleModalToggle" aria-hidden="true" aria-labelledby="exampleModalToggleLabel" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content align-items-center">
      <div class="modal-header">
        <h1 class="modal-title fs-5 text-center" id="exampleModalToggleLabel">Add Address</h1>
        <!-- <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button> -->
      </div>
      <%= form_for Address.new, url: address_index_path ,html: {class: "h-65 w-75"} do |f|%>
        <div>
          <%= f.hidden_field :user_id %>
          <%= f.text_field :street, class: "form-control mb-2", placeholder: "Street Name" %>
          <%= f.text_field :city, class: "form-control mb-2", placeholder: "City" %>
          <%= f.text_field :state, class: "form-control mb-2", placeholder: "State" %>
          <%= f.text_field :pin_code, class: "form-control mb-2", placeholder: "PIN Code" %>
          <div class="d-flex justify-content-center gap-2 mt-3">
            <%= f.check_box :default %>
            <%= f.label :default, 'Make this your default address', class:"fs-6 text-secondary fw-normal" %>
          </div>
          
        </div>
        <div class="d-flex flex-column align-items-center my-4 gap-3">
          <%= f.submit "Submit", class: "btn btn-primary "%>
        </div>
        </div>
      <%end%>
      
    </div>
  </div>
</div>