config/routes.rb
Rails.application.routes.draw do
  devise_for :users,controllers:{
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    recoverables: 'users/recoverables'
  }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")

  root "products#index" 

  resources :users, except: [:new, :create] do
    resources :orders
    resources :order_items, only: [:update]
    member do
      get '/products', to: 'users#products'
    end
  end

  namespace :admin do
    resources :roles
  end

  namespace :admin do
    resources :products, only: [:index]
  end

  resources :products do
    member do
      get '/product_stock', to: 'products#product_stocks'
    end
  end 

  namespace :admin do
    resources :categories do
    end
  end

  resources :categories do
    member do
      get '/product/:id', to: 'products#show', as: :see_product
    end
  end
  

  resources :product_stocks, only: [:index, :update, :create, :destroy, :edit]

  resources :address, only: [:index, :update, :create, :destroy, :edit]


  resources :cart_items, path: :cart, only: [:index, :create, :destroy] do
    member do
      patch '/increment', to: 'cart_items#increment'
      patch '/decrement', to: 'cart_items#decrement'
    end
  end

  get '/orders', to: 'orders#my_order'
  post '/order_verify/:id', to: 'orders#create'
  get ':id/payment', to: 'orders#payment', as: "payment"
  get '/checkout', to: 'orders#new'
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :categories_products, dependent: :destroy   
  has_many :products, through: :categories_products
  belongs_to :parent, class_name: 'Category', optional: true
  has_many :subcategories, class_name: 'Category', foreign_key: 'parent_id'
  
  validates :name, presence: true
end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < ApplicationController
    before_action :authenticate_user!

    def index
      @categories = Category.all
      authorize @categories
    end

    def new
      @category = Category.new
      authorize @category
    end

    def show
      authorize category
    end

    def create
      @category = Category.new(category_params)
      if @category.save
        redirect_to admin_categories_path, notice: "Category Created Successfully"
      else
        flash.now[:alert] = @category.errors.full_messages.to_sentence
        render :new, status: :unprocessable_entity
      end
    end
    
    def edit
      authorize category
    end

    def update
      authorize category
      if @category.update(category_params)
        redirect_to admin_categories_path, notice: "Category Updated Successfully"
      else
        flash.now[:alert] = category.errors.full_messages.join(', ')
        render :new, status: :unprocessable_entity
      end
    end

    def destroy
      authorize category
      @category.destroy
      redirect_to admin_categories_path, notice: "category Deleted Successfully"
    end

    private

    def category_params
      params.require(:category).permit(:name, :description, :parent_id)
    end

    def category
      @category ||= Category.find(params[:id])
      rescue ActiveRecord::RecordNotFound => e
        redirect_to '/404', alert: "Category Not Found"
    end
  end
end

app/views/categories/edit.html.erb
<%= stylesheet_link_tag "new_user.css", "data-turbo-track": "reload" %>

<div class="back-btn">
    <%= link_to '<-Back', categories_path %>
</div>

<div class="h-100">
    <div class="container ">
        <div class="form-box shadow" style="height: 40vh;">
            <%= form_for @category, html: { class: ' d-flex justify-center'}  do |f| %>

            <h1>Categoy Update</h1>

                <div>
                    <%= f.text_field :name ,placeholder:" Title", class:"form-control" %>
                </div>
                <div>
                    <%= f.text_field :description ,placeholder:" Description", class:"form-control"  %>
                </div>
                <div>
                    <%= f.label :parent_id, "Select Parent Category (If Exist)", class: "form-label" %>
                    <%= f.collection_select :parent_id, Category.all, :id, :name, { include_blank: 'None' }, class: 'form-control max-h', size: "2"  %>
                </div>
                <div>
                <%= f.submit "Update", class:"btn btn-outline-primary" %>
                </div>

            <% end %>
        </div>
    </div>
</div>

app/views/categories/index.html.erb
<%= stylesheet_link_tag "users.css", "data-turbo-track": "reload" %>

<h1 align="center" class="my-5 py-5">Categories List</h1>

<table align="center" class="shadow">
    <tr class="border-bottom">
        <th>
            Seriel No
        </th>
        <th>
            Category
        </th>
        <th>
            Description
        </th>
        <th>
            Actions
        </th>
        
    </tr>
    
    <% @categories.each_with_index do |category,i| %>
    

        <tr>
            
            <div class="row">
                <td>
                    <%= i+1 %>
                </td>
                <td>
                <% unless category.subcategories.empty? %>
                    <div>
                    <div class="accordion" id="accordionExample">
                        <div class="accordion-item">
                            <h2 class="accordion-header">
                                <button class="accordion-button collapsed fs-5 fw-medium" type="button" data-bs-toggle="collapse" data-bs-target="#collapse<%= i %>" aria-expanded="true" aria-controls="collapseOne">
                                    <%= category.name %>
                                </button>
                            </h2>
                            <div id="collapse<%= i %>" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
                                <% category.subcategories.pluck(:name).each do |item| %>
                                    <div class="accordion-body">
                                    <%= item.humanize %>
                                </div>
                                <% end %> 
                                
                            </div>
                        </div>
                    </div>
                </div>
                <% else %>
                <%= category.name %>
                <% end %>
            </td>
                <td>
                    <%= category.description %>
                </td>                                                          
                <td>
                    <%= link_to category_path(category),class:"btn btn-outline-primary" do %>
                        <i class="bi bi-eye-fill" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Show Category"></i>
                    <% end %>
                    <%= link_to edit_category_path(category),class:"btn btn-outline-dark"  do %>
                        <i class="bi bi-pen-fill" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Edit Category"></i>
                    <% end %>
                    <%= link_to category_path(category), data: { turbo_method: :delete, turbo_confirm: 'Are you sure to delete the Category?' },class:"btn btn-outline-danger" do %>
                        <i class="bi bi-trash-fill" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Delete Category"></i>
                    <% end %>
                   
            </div>
            

        </tr>
    <% end %>
    
</table>

<div align="center" class="mt-4">
    <%= link_to 'Add Another', new_category_path,class:"btn btn-outline-success" %>
</div>

app/views/categories/new.html.erb
<%= stylesheet_link_tag "new_user.css", "data-turbo-track": "reload" %>

<div class="back-btn">
    <%= link_to '<-Back', categories_path %>
</div>

<div>
    <div class="container">
        <div class="form-box shadow-lg">
            <%= form_for @category, html: { class: 'form-control d-flex justify-center' } do |f| %>

                <h1 class="text-dark">Add Category</h1>
                
                <div>
                    <%= f.text_field :name, placeholder: "Category Name", class: "form-control" %>
                </div>
                
                <div>
                    <%= f.text_field :description, placeholder: "Description", class: "form-control" %>
                </div>
                
                <div>
                    <%= f.label :parent_id, "Select Parent Category (If Exist)", class: "form-label" %>
                    <%= f.collection_select :parent_id, Category.all, :id, :name, { include_blank: 'None' }, class: 'form-control max-h', size: "2"  %>
                </div>
                
                <div>
                    <%= f.submit "Add", class: "btn btn-outline-primary" %>
                </div>

            <% end %>
        </div>
    </div>
</div>

app/views/categories/show.html.erb
<%= stylesheet_link_tag "users_show.css", "data-turbo-track": "reload"%>

<div class="d-flex align-items-center main" style="height: 90vh;">
    <div class = "container d-flex justify-content-center align-items-center shadow p-3 mb-5 bg-body-tertiary rounded show_container flex-column w-50 h-50 mt-5">
    <p class="h1 text-center mb-5">Category Details</p>

    <div class = "mb-5">
        <span class = "text-center fw-medium fs-4">Name : </span> 
        <span class = "fw-light fs-5"><%= @category.name %></span>
    </div>
    <div class = "mb-5">
        <span class = "text-center fw-medium fs-4">Description : </span> 
        <span class = "fw-light fs-5"><%= @category.description %></span>
    </div>
    <div class = "mt-5">
        <%= link_to "Edit", edit_category_path(@category), class: "btn btn-primary btn-lg"%>
    </div>
    </div>
    
</div>